# US Crime Prediction - Communities and Crime Unnormalized Dataset
---
- **Objetivo:** El presente notebook busca realizar un analisis exploratorio del dataset communities and crime unnormalized en donde se observaran las correlaciones y la estructura de los datos, ademas, se experimentara con combinaciones de los atributos y se generaran graficos estadisticos (histogramas) con el fin de identificar que features son informativos, que problemas estructurales tiene el dataset y que decisiones de preprocesamiento seran necesarias antes de entrenar un modelo.

- **Autor:** Alejandro Santos
- **Fecha:** 26/05/2026
- **Dataset:** UC Irvine Communities and Crime Unnormalized Dataset

## 1. Carga de datos

Se usa cargar_data_uci() para descargar y almacenar el dataset localmente. La funcion recoge la informacion desde la plataforma de UC Irvine.

- **Lo que se quiere verificar:** Que el archivo se descargo correctamente y que el shape (tama;o) es el esperado (2215 registros y 147 columnas)

In [19]:
from src.data_fnc.load_data import cargar_data_uci
import pandas as pd

In [20]:
df = cargar_data_uci(211)

Dataset cargado y guardado en: data\raw\dataset_211.csv

In [21]:
df.head()

,communityname,countyCode,communityCode,fold,State,pop,perHoush,pctBlack,pctWhite,pctAsian,...,burglaries,burglPerPop,larcenies,larcPerPop,autoTheft,autoTheftPerPop,arsons,arsonsPerPop,violentPerPop,nonViolPerPop
0,BerkeleyHeightstownship,39.0,5320.0,1,NJ,11980,3.10,1.37,91.78,6.50,...,14.0,114.85,138.0,1132.08,16.0,131.26,2.0,16.41,41.02,1394.59
1,Marpletownship,45.0,47616.0,1,PA,23123,2.82,0.80,95.57,3.44,...,57.0,242.37,376.0,1598.78,26.0,110.55,1.0,4.25,127.56,1955.95
2,Tigardcity,NaN,NaN,1,OR,29344,2.43,0.74,94.33,3.43,...,274.0,758.14,1797.0,4972.19,136.0,376.30,22.0,60.87,218.59,6167.51
3,Gloversvillecity,35.0,29443.0,1,NY,16656,2.40,1.70,97.35,0.50,...,225.0,1301.78,716.0,4142.56,47.0,271.93,NaN,NaN,306.64,NaN
4,Bemidjicity,7.0,5068.0,1,MN,11245,2.76,0.53,89.16,1.17,...,91.0,728.93,1060.0,8490.87,91.0,728.93,5.0,40.05,NaN,9988.79

In [22]:
print(f"Shape: {df.shape}")

Shape: (2215, 147)

In [27]:
# Eliminacion de otras columnas que eran posibles targets pero que en este caso no se utilizaran

df = df.drop(columns=['murders',
                      'murdPerPop',
                      'rapes',
                      'rapesPerPop',
                      'robbbPerPop',
                      'assaults',
                      'assaultPerPop',
                      'burglaries',
                      'burglPerPop',
                      'larcenies',
                      'larcPerPop',
                      'autoTheft',
                      'autoTheftPerPop',
                      'arsons',
                      'arsonsPerPop',
                      'violentPerPop',
                      'nonViolPerPop'])

In [30]:
print(f"Shape: {df.shape}")

Shape: (2215, 130)

## 2. Exploracion inicial del dataset

Antes de cualquier transformacion necesitamos responder las siguientes preguntas que condicionaran todo el preprocesamiento:

- Que tan complejo esta? -- Nulos criticos pueden descartar features enteras
- Existen variables categoricas?
- Las escalas son comparables? -- Determina si necesitamos StandardScaler o RobustScaler
- Que tan asimetricos son los features? -- Gran asimetria positiva (Power law distribution) necesita ser transformada logaritmicamente, si no es tan exagerada puede transformarse mediante raiz cuadrada
- Hay desbalance de clases? -- Determina si estratificamos el split o aplicamos SMOTE
- Que features estan mas correlacionados con el target? -- Determina si necesitamos talvez combinar features para que ganen capacidad predictiva

### 2.1. Estructura y nulos

In [28]:
## Configuracion de pandas para que muestre todas las columnas.
pd.set_option('display.max_columns', None)

In [ ]:
df.describe()

,countyCode,communityCode,fold,pop,perHoush,pctBlack,pctWhite,pctAsian,pctHisp,pct12-21,pct12-29,pct16-24,pct65up,persUrban,pctUrban,medIncome,pctWwage,pctWfarm,pctWdiv,pctWsocsec,pctPubAsst,pctRetire,medFamIncome,perCapInc,whitePerCap,blackPerCap,NAperCap,asianPerCap,otherPerCap,hispPerCap,persPoverty,pctPoverty,pctLowEdu,pctNotHSgrad,pctCollGrad,pctUnemploy,pctEmploy,pctEmployMfg,pctEmployProfServ,pctOccupManu,pctOccupMgmt,pctMaleDivorc,pctMaleNevMar,pctFemDivorc,pctAllDivorc,persPerFam,pct2Par,pctKids2Par,pctKids-4w2Par,pct12-17w2Par,pctWorkMom-6,pctWorkMom-18,kidsBornNevrMarr,pctKidsBornNevrMarr,numForeignBorn,pctFgnImmig-3,pctFgnImmig-5,pctFgnImmig-8,pctFgnImmig-10,pctImmig-3,pctImmig-5,pctImmig-8,pctImmig-10,pctSpeakOnlyEng,pctNotSpeakEng,pctLargHousFam,pctLargHous,persPerOccupHous,persPerOwnOccup,persPerRenterOccup,pctPersOwnOccup,pctPopDenseHous,pctSmallHousUnits,medNumBedrm,houseVacant,pctHousOccup,pctHousOwnerOccup,pctVacantBoarded,pctVacant6up,medYrHousBuilt,pctHousWOphone,pctHousWOplumb,ownHousLowQ,ownHousMed,ownHousUperQ,ownHousQrange,rentLowQ,rentMed,rentUpperQ,rentQrange,medGrossRent,medRentpctHousInc,medOwnCostpct,medOwnCostPctWO,persEmergShelt,persHomeless,pctForeignBorn,pctBornStateResid,pctSameHouse-5,pctSameCounty-5,pctSameState-5,numPolice,policePerPop,policeField,policeFieldPerPop,policeCalls,policCallPerPop,policCallPerOffic,policePerPop2,racialMatch,pctPolicWhite,pctPolicBlack,pctPolicHisp,pctPolicAsian,pctPolicMinority,officDrugUnits,numDiffDrugsSeiz,policAveOT,landArea,popDensity,pctUsePubTrans,policCarsAvail,policOperBudget,pctPolicPatrol,gangUnit,pctOfficDrugUnit,policBudgetPerPop,robberies
count,994.000000,991.000000,2215.000000,2.215000e+03,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2.215000e+03,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2214.000000,2215.000000,2.215000e+03,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2.215000e+03,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,2215.000000,343.000000,343.000000,343.000000,343.000000,3.430000e+02,3.430000e+02,343.000000,343.000000,343.000000,343.000000,343.000000,343.000000,343.000000,343.000000,343.000000,343.000000,343.000000,2215.000000,2215.000000,2215.000000,343.000000,3.430000e+02,343.000000,343.000000,2215.000000,3.430000e+02,2214.000000
mean,65.587525,45209.251261,5.494357,5.311798e+04,2.707327,9.335102,83.979819,2.670203,7.950176,14.445837,27.644840,13.975142,11.836393,4.773472e+04,70.465309,33984.696163,78.312758,0.881842,43.750935,26.409418,6.801445,15.969002,39857.055079,15603.524605,16567.698420,11541.749436,12229.191422,14227.989616,9442.765131,11018.998194,7.590853e+03,11.620537,9.186646,22.305120,23.056876,6.045242,62.021612,18.228907,24.532298,13.819165,28.209201,9.127585,30.683517,12.325300,10.812515,3.129698,74.059129,71.227255,81.865422,75.521788,60.542641,68.854795,2141.418962,3.115499,6.277274e+03,13.525693,20.421287,27.544181,34.733928,1.099124,1.697463,2.307503,2.943761,87.074993,2.405792,5.386619,3.915788,2.615842,2.740483,2.367138,66.369454,4.132438,45.405341,2.640632,1748.368849,92.933973,63.368298,2.778524,34.773887,1962.623476,4.289824,0.425273,88695.802257,113097.523251,145318.257788,56622.455530,329.966591,428.537246,527.252822,197.286230,501.466366,26.298104,20.990158,13.010203,66.953499,17.823476,7.340302,61.539630,51.538596,77.411079,88.111865,499.198251,246.490962,432.559767,210.844781,2.524050e+05,1.206517e+05,523.658309,246.493586,85.499679,82.515831,9.263294,5.459767,0.681283,15.242245,26.288630,8.816327,119.114286,27.419955,2783.835034,3.041124,185.478134,3.217602e+07,87.130933,4.285714,0.980163,1.535779e+05,237.952123
std,117.831399,25425.861573,2.872924,2.046203e+05,0.334120,14.247156,16.419080,4.473843,14.589832,4.518623,6.181517,5.970747,4.777565,2.056067e+05,44.080275,13424.680011,7.950672,0.689006,12.787925,8.295604,4.700335,4.622553,14251.206032,6281.558523,6346.840251,9232.102062,14853.836177,9881.266395,7926.466713,5884.063446,3.936146e+04,8.600352,6.666703,10.989517,12.687213,2.895618,8.312045,8.099281,6.659470,6.430264,9.326123,2.802747,8.127991,3.262613,3.000883,0.240743,10.525952,12.045048,12.263736,10.365262,8.008937,6.679960,14692.582838,3.127681,5.541965e+04,9.780098,12.410355,14.368813,16.327322,1.595766,2.461060,3.286648,4.246468,14.076087,4.210368,3.794309,3.175770,0.315646,0.297421,0.391806,14.182588,5.599131,13.778347,0.512686,6503.866478,5.040736,13.970057,3.592396,13.911468,11.166555,4.088175,0.426188,66670.781534,81906.362277,99030.913816,39106.498041,144.138461,170.706644,199.290780,85.205688,169.271735,2.979297,2.987622,1.419679,564.253149,245.452553,8.418476,16.750061,10.517926,10.878186,7.287836,1681.472251,273.799162,1493.708385,235.478815,6.894498e+05,1.482113e+05,307.839007,273.798409,10.941312,15.332612,11.021424,10.604533,1.706344,14.826756,100.821921,2.836391,92.495186,109.822600,2828.993341,4.912917,318.542834,1.104566e+08,10.349612,4.064538,2.877128,2.030409e+05,2250.720788
min,1.000000,70.000000,1.000000,1.000500e+04,1.600000,0.000000,2.680000,0.030000,0.120000,4.580000,9.380000,4.640000,1.660000,0.000000e+00,0.000000,8866.000000,31.680000,0.000000,5.810000,4.810000,0.180000,3.460000,10447.000000,5237.000000,5472.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.800000e+01,0.640000,0.200000,1.460000,1.630000,1.320000,24.820000,2.050000,8.690000,1.370000,6.480000,2.130000,12.060000,3.350000,2.830000,2.290000,22.970000,18.300000,8.700000,20.200000,24.420000,41.950000,0.000000,0.000000,2.000000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.150000,0.000000,0.960000,0.440000,1.580000,1.610000,1.550000,13.930000,0.050000,3.060000,1.000000,36.000000,37.470000,16.860000,0.000000,3.120000,1939.000000,0.000000,0.000000,14999.000000,19500.000000,28200.000000,0.000000,99.000000,120.000000,182.000000,0.000000,192.000000,14.900000,14.000000,10.100000,0.000000,0.000000,0.180000,6.750000,11.830000,27.950000,32.830000,65.000000,29.400000,14.000000,19.210000,2.100000e+03,2.704800e+03,20.800000,29.400000,42.150000,1.600000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.900000,10.000000,0.000000,20.000000,2.380215e+06,10.850000,0.000000,0.000000,1.526040e+04,0.000000
25%,11.000000,22887.000000,3.000000,1.436600e+04,2.500000,0.860000,76.320000,0.620000,0.930000,12.250000,24.415000,11.320000,8.750000,0.000000e+00,0.000000,23817.000000,73.400000,0.460000,34.680000,20.770000,3.270000,12.875000,29538.000000,11602.500000,12610.500000,6742.500000,6345.000000,8285.500000,5528.250000,7274.000000,9.125000e+02,4.510000,4.640000,13.920000,14.095000,4.045000,56.490000,12.215000,20.075000,9.130000,21.910000,7.110000,25.450000,9.860000,8.575000,2.990000,67.900000,63.990000,74.780000,70.170000,55.430000,64.900000,147.000000,1.070000,4.000000e+02,6.695000,11.255000,17.205000,22.725000,0.170000,0.280000,0.390000,0.520000,84.380000,0.510000,3.390000,2.370000,2.410000,2.550000,2.110000,57.285000,1.290000,37.505000,2.000000,304.500000,91.290000,54.820000,0.720000,24.480000,1956.000000,0.905000,0.160000,41500.000000,56200.000000,74300.000000,32200.000000,213.500000,289.500000,366.000000,139.000000,364.000000,24.300000,18.700000,12.000000,0.000000,0.000000,2.060000,50.110000,44.995000,72.060000,85.200000,131.000000,149.115000,114.000000,132.245000,4.986450e+04,6.484505e+04,343.350000,149.150000,79.435000,76.230000,2.020000,0.415000,0.000000,4.950000,6.000000,7.000000,55.100000,7.300000,1181.900000,0.360000,54.000000,7.275060e+06,84.295000,0.000000,0.000000,8.809435e+04,5.000000
50%,27.000000,46925.000000,5.000000,2.279200e+04,2.660000,2.870000,90.350000,1.230000,2.180000,13.620000,26.780000,12.540000,11.730000,1.804100e+04,100.000000,31441.000000,78.610000,0.690000,42.880000,26.590000,5.610000,15.650000,36678.000000,14101.000000,15073.000000,9777.000000,9895.000000,12250.000000,8186.000000,9721.000000,2.142000e+03,9.330000,7.740000,21.380000,19.650000,5.450000,62.440000,17.300000,23.390000,13.150000,26.240000,9.150000,29.000000,12.520000,10.900000,3.100000,75.030000,72.530000,83.990000,76.920000,60.710000,69.230000,352.000000,2.040000,1.024000e+03,12.260000,19.080000,26.720000,34.790000,0.500000,0.750000,1.040000,1.310000,92.180000,0.920000,4.280000,3.050000,2.570000,2.710000,2.290000,65.910000,2.340000,46.390000,3.000000,558.000000,94.210000,62.830000,1.660000,34.100000,1964.000000,2.850000,0.320000,65500.000000,82800.000000,106700.000000,43400.000000,307.000000,397.000000,486.000000,171.000000,467.000000,26.100000,21.000000,12.800000,0.000000,0.000000,4.310000,64.490000,52.170000,79.490000,90.030000,173.000000,196.010000,152.000000,170.270000,9.000000e+04,9.103460e+04,443.200000,196.000000,87.930000,86.180000,5.000000,2.040000,0.000000,11.370000,12.000000,9.000000,98.700000,13.700000,2027.300000,1.220000,86.000000,1.116411e+07,89.580000,5.000000,0.000000,1.145820e+05,19.000000
75%,80.500000,65805.000000,8.000000,4.302400e+04,2.850000,11.145000,96.225000,2.670000,7.810000,15.360000,29.205000,14.345000,14.415000,4.191800e+04,100.000000,41480.500000,84.030000,1.100000,52.740000,31.715000,9.105000,18.755000,46999.000000,17795.000000,18609.500000,14526.000000,14757.500000,17327.500000,11525.500000,13418.000000,4.988000e+03,16.905000,11.835000,29.195000,29.055000,7.440000,67.825000,23.400000,27.590000,17.665000,32.815000,11.050000,33.410000,14.745000,12.985000,3.220000,81.900000,80.395000,91.675000,82.765000,65.985000,73.495000,1031.500000,3.910000,3.302000e+03,17.950000,27.445000,36.495000,46.185000,1.310000,2.015000,2.700000,3.455000,95.455000,2.270000,5.870000,4.210000,2.770000,2.900000,2.530000,76.580000,4.730000,53.515000,3.000000,1228.000000,96.020000,72.645000,3.430000,43.970000,1971.000000,6.805000,0.555000,121500.000000,150600.000000,188000.000000,65450.000000,421.000000,544.000000,659.500000,232.500000,615.000000,28.000000,23.100000,13.700000,22.000000,1.000000,9.250000,74.855000,58.740000,85.135000,93.010000,314.000000,260.650000,285.500000,226.815000,1.719235e+05,1.303246e+05,637.250000,260.650000,93.645000,93.340000,14.065000,6.215000,0.650000,19.740000,23.000000,10.500000,153.550000,26.100000,3321.700000,3.365000,189.500000,2.014754e+07,93.200000,10.000000,0.000000,1.556557e+05,70.000000
max,840.000000,94597.000000,10.000000,7.322564e+06,5.280000,96.670000,99.630000,57.460000,95.290000,54.400000,70.510000,63.620000,52.770000,7.322564e+06,100.000000,123625.000000,96.760000,6.530000,89.040000,76.390000,44.820000,45.510000,139008.000000,63302.000000,68850.000000,212120.000000,480000.000000,106165.000000,137000.000000,54648.000000,1.384994e+06,58.000000,49.890000,73.660000,79.180000,31.230000,84.670000,50.030000,62.670000,44.270000,64.970000,20.080000,76.600000,23.920000,22.230000,4.640000,93.600000,92.580000,100.000000,97.340000,87.970000,89.370000,527557.000000,27.350000,2.082931e+06,64.290000,76.160000,80.810000,88.000000,13.710000,19.930000,25.340000,32.630000,98.980000,38.330000,34.870000,30.870000,4.520000,4.480000,4.730000,97.240000,59.490000,95.340000,4.000000,172768.000000,99.000000,96.490000,39.890000,82.130000,1987.000000,23.880000,5.330000,500001.000000,500001.000000,500001.000000,331000.000000,1001.000000,1001.000000,1001.000000,803.000000,1001.000000,35.100000,32.700000,23.400000,23383.000000,10447.000000,60.400000,93.140000,78.560000,96.590000,99.900000,25655.000000,3437.230000,22496.000000,3290.620000,8.328470e+06,1.926282e+06,2162.500000,3437.200000,100.000000,100.000000,67.310000,98.400000,18.570000,98.400000,1773.000000,15.000000,634.700000,3569.800000,44229.900000,54.330000,3187.000000,1.617293e+09,99.940000,10.000000,48.440000,2.422367e+06,86001.000000

In [32]:
df.info(verbose=True, show_counts=True) # verbose y show_counts para ignorar el limite de columnas

<class 'pandas.DataFrame'>
RangeIndex: 2215 entries, 0 to 2214
Data columns (total 130 columns):
 #    Column               Non-Null Count  Dtype
---   ------               --------------  -----
 0    communityname        2215 non-null   str
 1    countyCode           994 non-null    float64
 2    communityCode        991 non-null    float64
 3    fold                 2215 non-null   int64
 4    State                2215 non-null   str
 5    pop                  2215 non-null   int64
 6    perHoush             2215 non-null   float64
 7    pctBlack             2215 non-null   float64
 8    pctWhite             2215 non-null   float64
 9    pctAsian             2215 non-null   float64
 10   pctHisp              2215 non-null   float64
 11   pct12-21             2215 non-null   float64
 12   pct12-29             2215 non-null   float64
 13   pct16-24             2215 non-null   float64
 14   pct65up              2215 non-null   float64
 15   persUrban            2215 non-null   int64
 16   pctUrban             2215 non-null   float64
 17   medIncome            2215 non-null   int64
 18   pctWwage             2215 non-null   float64
 19   pctWfarm             2215 non-null   float64
 20   pctWdiv              2215 non-null   float64
 21   pctWsocsec           2215 non-null   float64
 22   pctPubAsst           2215 non-null   float64
 23   pctRetire            2215 non-null   float64
 24   medFamIncome         2215 non-null   int64
 25   perCapInc            2215 non-null   int64
 26   whitePerCap          2215 non-null   int64
 27   blackPerCap          2215 non-null   int64
 28   NAperCap             2215 non-null   int64
 29   asianPerCap          2215 non-null   int64
 30   otherPerCap          2214 non-null   float64
 31   hispPerCap           2215 non-null   int64
 32   persPoverty          2215 non-null   int64
 33   pctPoverty           2215 non-null   float64
 34   pctLowEdu            2215 non-null   float64
 35   pctNotHSgrad         2215 non-null   float64
 36   pctCollGrad          2215 non-null   float64
 37   pctUnemploy          2215 non-null   float64
 38   pctEmploy            2215 non-null   float64
 39   pctEmployMfg         2215 non-null   float64
 40   pctEmployProfServ    2215 non-null   float64
 41   pctOccupManu         2215 non-null   float64
 42   pctOccupMgmt         2215 non-null   float64
 43   pctMaleDivorc        2215 non-null   float64
 44   pctMaleNevMar        2215 non-null   float64
 45   pctFemDivorc         2215 non-null   float64
 46   pctAllDivorc         2215 non-null   float64
 47   persPerFam           2215 non-null   float64
 48   pct2Par              2215 non-null   float64
 49   pctKids2Par          2215 non-null   float64
 50   pctKids-4w2Par       2215 non-null   float64
 51   pct12-17w2Par        2215 non-null   float64
 52   pctWorkMom-6         2215 non-null   float64
 53   pctWorkMom-18        2215 non-null   float64
 54   kidsBornNevrMarr     2215 non-null   int64
 55   pctKidsBornNevrMarr  2215 non-null   float64
 56   numForeignBorn       2215 non-null   int64
 57   pctFgnImmig-3        2215 non-null   float64
 58   pctFgnImmig-5        2215 non-null   float64
 59   pctFgnImmig-8        2215 non-null   float64
 60   pctFgnImmig-10       2215 non-null   float64
 61   pctImmig-3           2215 non-null   float64
 62   pctImmig-5           2215 non-null   float64
 63   pctImmig-8           2215 non-null   float64
 64   pctImmig-10          2215 non-null   float64
 65   pctSpeakOnlyEng      2215 non-null   float64
 66   pctNotSpeakEng       2215 non-null   float64
 67   pctLargHousFam       2215 non-null   float64
 68   pctLargHous          2215 non-null   float64
 69   persPerOccupHous     2215 non-null   float64
 70   persPerOwnOccup      2215 non-null   float64
 71   persPerRenterOccup   2215 non-null   float64
 72   pctPersOwnOccup      2215 non-null   float64
 73   pctPopDenseHous      2215 non-null   float64
 74   pctSmallHousUnits    2215 non-null   float64
 75   medNumBedrm          2215 non-null   int64
 76   houseVacant          2215 non-null   int64
 77   pctHousOccup         2215 non-null   float64
 78   pctHousOwnerOccup    2215 non-null   float64
 79   pctVacantBoarded     2215 non-null   float64
 80   pctVacant6up         2215 non-null   float64
 81   medYrHousBuilt       2215 non-null   int64
 82   pctHousWOphone       2215 non-null   float64
 83   pctHousWOplumb       2215 non-null   float64
 84   ownHousLowQ          2215 non-null   int64
 85   ownHousMed           2215 non-null   int64
 86   ownHousUperQ         2215 non-null   int64
 87   ownHousQrange        2215 non-null   int64
 88   rentLowQ             2215 non-null   int64
 89   rentMed              2215 non-null   int64
 90   rentUpperQ           2215 non-null   int64
 91   rentQrange           2215 non-null   int64
 92   medGrossRent         2215 non-null   int64
 93   medRentpctHousInc    2215 non-null   float64
 94   medOwnCostpct        2215 non-null   float64
 95   medOwnCostPctWO      2215 non-null   float64
 96   persEmergShelt       2215 non-null   int64
 97   persHomeless         2215 non-null   int64
 98   pctForeignBorn       2215 non-null   float64
 99   pctBornStateResid    2215 non-null   float64
 100  pctSameHouse-5       2215 non-null   float64
 101  pctSameCounty-5      2215 non-null   float64
 102  pctSameState-5       2215 non-null   float64
 103  numPolice            343 non-null    float64
 104  policePerPop         343 non-null    float64
 105  policeField          343 non-null    float64
 106  policeFieldPerPop    343 non-null    float64
 107  policeCalls          343 non-null    float64
 108  policCallPerPop      343 non-null    float64
 109  policCallPerOffic    343 non-null    float64
 110  policePerPop2        343 non-null    float64
 111  racialMatch          343 non-null    float64
 112  pctPolicWhite        343 non-null    float64
 113  pctPolicBlack        343 non-null    float64
 114  pctPolicHisp         343 non-null    float64
 115  pctPolicAsian        343 non-null    float64
 116  pctPolicMinority     343 non-null    float64
 117  officDrugUnits       343 non-null    float64
 118  numDiffDrugsSeiz     343 non-null    float64
 119  policAveOT           343 non-null    float64
 120  landArea             2215 non-null   float64
 121  popDensity           2215 non-null   float64
 122  pctUsePubTrans       2215 non-null   float64
 123  policCarsAvail       343 non-null    float64
 124  policOperBudget      343 non-null    float64
 125  pctPolicPatrol       343 non-null    float64
 126  gangUnit             343 non-null    float64
 127  pctOfficDrugUnit     2215 non-null   float64
 128  policBudgetPerPop    343 non-null    float64
 129  robberies            2214 non-null   float64
dtypes: float64(100), int64(28), str(2)
memory usage: 2.2 MB

In [72]:
type(df)

pandas.DataFrame

In [83]:
from tabulate import tabulate

# Reporte de nulos por columna. Con <5% podemos eliminar filas.
# Con >5% habria que evaluar imputacion o eliminar la feature.

def porcentaje_nulos(dataframe):
    '''
        Calcula el porcentaje de nulos de cada feature
        en un dataframe, clasifica aquellas que superan el umbral de
        0.05% y genera dos tablas formateadas, una con un resumen general
        y una lista de alerta.

        Args:
            dataframe (pandas.DataFrame): Dataframe del cual se desea saber
                si existe presencia de nulos.
            
        Returns:
            None: La funcion no retorna ningun valor, imprime el reporte en la salida estandar (consola)
    '''
    nulos = (dataframe.isnull().sum() / len(df) * 100).round(2)

    matriz = []
    revisar = []
    
    for key, value in nulos.items():
        if value > 0.05:
            matriz.append([key, value])
            revisar.append([key, value])
        else:
            matriz.append([key, value])
            

    print(tabulate(matriz, headers=['Feature', 'Porcentaje', 'Revisar']))

    print("\n--Features a revisar por alto porcentaje de nulos--")

    print(f"\n{tabulate(revisar, headers=['Features', 'Porcentaje'])}")

In [84]:
porcentaje_nulos(df)

Feature                Porcentaje
-------------------  ------------
communityname                0
countyCode                  55.12
communityCode               55.26
fold                         0
State                        0
pop                          0
perHoush                     0
pctBlack                     0
pctWhite                     0
pctAsian                     0
pctHisp                      0
pct12-21                     0
pct12-29                     0
pct16-24                     0
pct65up                      0
persUrban                    0
pctUrban                     0
medIncome                    0
pctWwage                     0
pctWfarm                     0
pctWdiv                      0
pctWsocsec                   0
pctPubAsst                   0
pctRetire                    0
medFamIncome                 0
perCapInc                    0
whitePerCap                  0
blackPerCap                  0
NAperCap                     0
asianPerCap                  0
otherPerCap                  0.05
hispPerCap                   0
persPoverty                  0
pctPoverty                   0
pctLowEdu                    0
pctNotHSgrad                 0
pctCollGrad                  0
pctUnemploy                  0
pctEmploy                    0
pctEmployMfg                 0
pctEmployProfServ            0
pctOccupManu                 0
pctOccupMgmt                 0
pctMaleDivorc                0
pctMaleNevMar                0
pctFemDivorc                 0
pctAllDivorc                 0
persPerFam                   0
pct2Par                      0
pctKids2Par                  0
pctKids-4w2Par               0
pct12-17w2Par                0
pctWorkMom-6                 0
pctWorkMom-18                0
kidsBornNevrMarr             0
pctKidsBornNevrMarr          0
numForeignBorn               0
pctFgnImmig-3                0
pctFgnImmig-5                0
pctFgnImmig-8                0
pctFgnImmig-10               0
pctImmig-3                   0
pctImmig-5                   0
pctImmig-8                   0
pctImmig-10                  0
pctSpeakOnlyEng              0
pctNotSpeakEng               0
pctLargHousFam               0
pctLargHous                  0
persPerOccupHous             0
persPerOwnOccup              0
persPerRenterOccup           0
pctPersOwnOccup              0
pctPopDenseHous              0
pctSmallHousUnits            0
medNumBedrm                  0
houseVacant                  0
pctHousOccup                 0
pctHousOwnerOccup            0
pctVacantBoarded             0
pctVacant6up                 0
medYrHousBuilt               0
pctHousWOphone               0
pctHousWOplumb               0
ownHousLowQ                  0
ownHousMed                   0
ownHousUperQ                 0
ownHousQrange                0
rentLowQ                     0
rentMed                      0
rentUpperQ                   0
rentQrange                   0
medGrossRent                 0
medRentpctHousInc            0
medOwnCostpct                0
medOwnCostPctWO              0
persEmergShelt               0
persHomeless                 0
pctForeignBorn               0
pctBornStateResid            0
pctSameHouse-5               0
pctSameCounty-5              0
pctSameState-5               0
numPolice                   84.51
policePerPop                84.51
policeField                 84.51
policeFieldPerPop           84.51
policeCalls                 84.51
policCallPerPop             84.51
policCallPerOffic           84.51
policePerPop2               84.51
racialMatch                 84.51
pctPolicWhite               84.51
pctPolicBlack               84.51
pctPolicHisp                84.51
pctPolicAsian               84.51
pctPolicMinority            84.51
officDrugUnits              84.51
numDiffDrugsSeiz            84.51
policAveOT                  84.51
landArea                     0
popDensity                   0
pctUsePubTrans               0
policCarsAvail              84.51
policOperBudget             84.51
pctPolicPatrol              84.51
gangUnit                    84.51
pctOfficDrugUnit             0
policBudgetPerPop           84.51
robberies                    0.05

--Features a revisar por alto porcentaje de nulos--

Features             Porcentaje
-----------------  ------------
countyCode                55.12
communityCode             55.26
numPolice                 84.51
policePerPop              84.51
policeField               84.51
policeFieldPerPop         84.51
policeCalls               84.51
policCallPerPop           84.51
policCallPerOffic         84.51
policePerPop2             84.51
racialMatch               84.51
pctPolicWhite             84.51
pctPolicBlack             84.51
pctPolicHisp              84.51
pctPolicAsian             84.51
pctPolicMinority          84.51
officDrugUnits            84.51
numDiffDrugsSeiz          84.51
policAveOT                84.51
policCarsAvail            84.51
policOperBudget           84.51
pctPolicPatrol            84.51
gangUnit                  84.51
policBudgetPerPop         84.51